"""Generate PDDL domains and problems, reproducibly.

Benchmarks live or die on their instance set, and hand-writing a scaling ladder
is tedious. Each generator here takes a size and a ``seed`` and emits PDDL text,
so a whole difficulty curve is one comprehension — and re-running the same seed
gives byte-identical files, which is what makes a published experiment
reproducible.

::

    from jupyddl.generator import generate, GENERATORS

    domain, problem = generate("blocksworld", size=10, seed=7)
    ladder = [generate("gripper", size=n, seed=1) for n in range(2, 12)]

Every generator is exercised by the test suite, which grounds and solves what it
produces — a generator that emits unsolvable or unparseable PDDL is a bug.
"""

from __future__ import annotations

import random
from typing import Optional

__all__ = [
    "GENERATORS",
    "generate",
    "describe_generators",
    "generate_blocksworld",
    "generate_gripper",
    "generate_logistics",
    "generate_rovers",
    "generate_random_strips",
    "generate_numeric_transport",
    "generate_temporal_workshop",
]


def _objects(prefix: str, count: int) -> list:
    return [f"{prefix}{i + 1}" for i in range(count)]


# --------------------------------------------------------------------------
# blocksworld
# --------------------------------------------------------------------------
BLOCKSWORLD_DOMAIN = """\
;; Blocksworld -- generated by jupyddl.generator
(define (domain blocksworld)
  (:requirements :strips :typing)
  (:types block - object)
  (:predicates
    (on ?x - block ?y - block)
    (ontable ?x - block)
    (clear ?x - block)
    (handempty)
    (holding ?x - block))

  (:action pick-up
    :parameters (?x - block)
    :precondition (and (clear ?x) (ontable ?x) (handempty))
    :effect (and (not (ontable ?x)) (not (clear ?x))
                 (not (handempty)) (holding ?x)))

  (:action put-down
    :parameters (?x - block)
    :precondition (holding ?x)
    :effect (and (not (holding ?x)) (clear ?x) (handempty) (ontable ?x)))

  (:action stack
    :parameters (?x - block ?y - block)
    :precondition (and (holding ?x) (clear ?y))
    :effect (and (not (holding ?x)) (not (clear ?y))
                 (clear ?x) (handempty) (on ?x ?y)))

  (:action unstack
    :parameters (?x - block ?y - block)
    :precondition (and (on ?x ?y) (clear ?x) (handempty))
    :effect (and (holding ?x) (clear ?y) (not (clear ?x))
                 (not (handempty)) (not (on ?x ?y)))))
"""


def _random_towers(blocks, rng) -> list:
    """Partition ``blocks`` into a random set of towers (bottom-first)."""
    shuffled = list(blocks)
    rng.shuffle(shuffled)
    towers: list = []
    index = 0
    while index < len(shuffled):
        height = rng.randint(1, max(1, len(shuffled) - index))
        towers.append(shuffled[index : index + height])
        index += height
    return towers


def _tower_facts(towers) -> list:
    facts = []
    for tower in towers:
        facts.append(f"(ontable {tower[0]})")
        for lower, upper in zip(tower, tower[1:]):
            facts.append(f"(on {upper} {lower})")
        facts.append(f"(clear {tower[-1]})")
    return facts


def generate_blocksworld(size: int = 6, seed: int = 0):
    """``size`` blocks in random towers, to be rearranged into other towers."""
    rng = random.Random(seed)
    blocks = _objects("b", max(2, size))
    start = _random_towers(blocks, rng)
    goal_towers = _random_towers(blocks, rng)
    while goal_towers == start and len(blocks) > 2:
        goal_towers = _random_towers(blocks, rng)

    goal_facts = []
    for tower in goal_towers:
        goal_facts.append(f"(ontable {tower[0]})")
        for lower, upper in zip(tower, tower[1:]):
            goal_facts.append(f"(on {upper} {lower})")

    problem = f"""\
;; {len(blocks)} blocks, seed {seed} -- generated by jupyddl.generator
(define (problem blocksworld-{len(blocks)}-{seed})
  (:domain blocksworld)
  (:objects {' '.join(blocks)} - block)
  (:init
    (handempty)
    {chr(10).join('    ' + f for f in _tower_facts(start)).strip()})
  (:goal (and
    {chr(10).join('    ' + f for f in goal_facts).strip()})))
"""
    return BLOCKSWORLD_DOMAIN, problem


# --------------------------------------------------------------------------
# gripper
# --------------------------------------------------------------------------
GRIPPER_DOMAIN = """\
;; Gripper -- generated by jupyddl.generator
(define (domain gripper)
  (:requirements :strips :typing)
  (:types room ball gripper - object)
  (:predicates
    (at-robby ?r - room)
    (at ?b - ball ?r - room)
    (free ?g - gripper)
    (carry ?b - ball ?g - gripper))

  (:action move
    :parameters (?from - room ?to - room)
    :precondition (at-robby ?from)
    :effect (and (at-robby ?to) (not (at-robby ?from))))

  (:action pick
    :parameters (?b - ball ?r - room ?g - gripper)
    :precondition (and (at ?b ?r) (at-robby ?r) (free ?g))
    :effect (and (carry ?b ?g) (not (at ?b ?r)) (not (free ?g))))

  (:action drop
    :parameters (?b - ball ?r - room ?g - gripper)
    :precondition (and (carry ?b ?g) (at-robby ?r))
    :effect (and (at ?b ?r) (free ?g) (not (carry ?b ?g)))))
"""


def generate_gripper(size: int = 4, seed: int = 0, grippers: int = 2):
    """``size`` balls to move from room A to room B. Plan length grows linearly.

    Unlike every other generator here, ``seed`` does not vary the instance:
    in gripper every ball starts in room A and must end in room B, so
    ``size`` and ``grippers`` determine the problem completely. The seed
    reaches only the problem name, which keeps generated files distinct.

    The consequence is worth stating because it is easy to miss: a
    train/test split that varies the seed and holds the size fixed produces
    the *same instance* twice for this domain. Vary ``size`` instead.
    """
    balls = _objects("ball", max(1, size))
    hands = _objects("gripper", max(1, grippers))
    init = ["(at-robby rooma)"]
    init += [f"(free {g})" for g in hands]
    init += [f"(at {b} rooma)" for b in balls]

    problem = f"""\
;; {len(balls)} balls, {len(hands)} grippers, seed {seed}
(define (problem gripper-{len(balls)}-{seed})
  (:domain gripper)
  (:objects
    rooma roomb - room
    {' '.join(balls)} - ball
    {' '.join(hands)} - gripper)
  (:init
    {chr(10).join('    ' + f for f in init).strip()})
  (:goal (and
    {chr(10).join(f'    (at {b} roomb)' for b in balls).strip()})))
"""
    return GRIPPER_DOMAIN, problem


# --------------------------------------------------------------------------
# logistics
# --------------------------------------------------------------------------
LOGISTICS_DOMAIN = """\
;; Logistics with action costs -- generated by jupyddl.generator
(define (domain logistics)
  (:requirements :strips :typing :action-costs)
  (:types
    truck airplane - vehicle
    package vehicle - thing
    airport location - place
    city - object)
  (:predicates
    (at ?t - thing ?p - place)
    (in ?p - package ?v - vehicle)
    (in-city ?p - place ?c - city))
  (:functions (total-cost))

  (:action load
    :parameters (?p - package ?v - vehicle ?l - place)
    :precondition (and (at ?p ?l) (at ?v ?l))
    :effect (and (not (at ?p ?l)) (in ?p ?v) (increase (total-cost) 1)))

  (:action unload
    :parameters (?p - package ?v - vehicle ?l - place)
    :precondition (and (in ?p ?v) (at ?v ?l))
    :effect (and (not (in ?p ?v)) (at ?p ?l) (increase (total-cost) 1)))

  (:action drive
    :parameters (?t - truck ?from - place ?to - place ?c - city)
    :precondition (and (at ?t ?from) (in-city ?from ?c) (in-city ?to ?c))
    :effect (and (not (at ?t ?from)) (at ?t ?to) (increase (total-cost) 2)))

  (:action fly
    :parameters (?a - airplane ?from - airport ?to - airport)
    :precondition (at ?a ?from)
    :effect (and (not (at ?a ?from)) (at ?a ?to) (increase (total-cost) 6))))
"""


def generate_logistics(size: int = 3, seed: int = 0, cities: int = 2):
    """``size`` packages across ``cities`` cities, each with an airport and depot."""
    rng = random.Random(seed)
    cities = max(2, cities)
    packages = _objects("pkg", max(1, size))
    city_names = _objects("city", cities)
    airports = [f"apt{i + 1}" for i in range(cities)]
    depots = [f"depot{i + 1}" for i in range(cities)]
    trucks = [f"truck{i + 1}" for i in range(cities)]

    init = ["(= (total-cost) 0)"]
    for i in range(cities):
        init.append(f"(in-city {airports[i]} {city_names[i]})")
        init.append(f"(in-city {depots[i]} {city_names[i]})")
        init.append(f"(at {trucks[i]} {depots[i]})")
    init.append(f"(at plane1 {airports[0]})")

    goals = []
    for package in packages:
        source = rng.randrange(cities)
        target = rng.randrange(cities)
        while target == source and cities > 1:
            target = rng.randrange(cities)
        init.append(f"(at {package} {rng.choice([airports[source], depots[source]])})")
        goals.append(f"(at {package} {rng.choice([airports[target], depots[target]])})")

    problem = f"""\
;; {len(packages)} packages, {cities} cities, seed {seed}
(define (problem logistics-{len(packages)}-{seed})
  (:domain logistics)
  (:objects
    {' '.join(city_names)} - city
    {' '.join(trucks)} - truck
    plane1 - airplane
    {' '.join(packages)} - package
    {' '.join(airports)} - airport
    {' '.join(depots)} - location)
  (:init
    {chr(10).join('    ' + f for f in init).strip()})
  (:goal (and
    {chr(10).join('    ' + g for g in goals).strip()}))
  (:metric minimize (total-cost)))
"""
    return LOGISTICS_DOMAIN, problem


# --------------------------------------------------------------------------
# rovers (ADL: disjunction + quantification)
# --------------------------------------------------------------------------
ROVERS_DOMAIN = """\
;; Rovers -- exercises disjunctive and quantified preconditions.
(define (domain rovers)
  (:requirements :strips :typing :adl)
  (:types rover waypoint objective - object)
  (:predicates
    (at ?r - rover ?w - waypoint)
    (can-traverse ?a ?b - waypoint)
    (visible ?o - objective ?w - waypoint)
    (imaged ?o - objective)
    (sampled ?w - waypoint)
    (analysed ?w - waypoint)
    (reported ?o - objective))

  (:action navigate
    :parameters (?r - rover ?from ?to - waypoint)
    :precondition (and (at ?r ?from) (can-traverse ?from ?to))
    :effect (and (not (at ?r ?from)) (at ?r ?to)))

  (:action sample
    :parameters (?r - rover ?w - waypoint)
    :precondition (and (at ?r ?w) (not (sampled ?w)))
    :effect (sampled ?w))

  (:action analyse
    :parameters (?w - waypoint)
    :precondition (sampled ?w)
    :effect (analysed ?w))

  ;; An objective can be imaged from any waypoint that sees it.
  (:action image
    :parameters (?r - rover ?o - objective)
    :precondition (exists (?w - waypoint) (and (at ?r ?w) (visible ?o ?w)))
    :effect (imaged ?o))

  ;; Reporting accepts either a picture or a full sample analysis.
  (:action report
    :parameters (?o - objective)
    :precondition (or (imaged ?o)
                      (exists (?w - waypoint)
                              (and (visible ?o ?w) (analysed ?w))))
    :effect (reported ?o)))
"""


def generate_rovers(size: int = 3, seed: int = 0, waypoints: int = 5):
    """``size`` objectives over a connected waypoint graph. Uses `or` and `exists`."""
    rng = random.Random(seed)
    waypoints = max(2, waypoints)
    points = _objects("wp", waypoints)
    objectives = _objects("obj", max(1, size))

    init = ["(at rover1 wp1)"]
    # A spanning path guarantees the graph is connected, so every instance is
    # solvable; the extra edges just give the planner choices.
    for a, b in zip(points, points[1:]):
        init.append(f"(can-traverse {a} {b})")
        init.append(f"(can-traverse {b} {a})")
    for _ in range(waypoints):
        a, b = rng.sample(points, 2)
        init.append(f"(can-traverse {a} {b})")

    for objective in objectives:
        for point in rng.sample(points, rng.randint(1, min(2, len(points)))):
            init.append(f"(visible {objective} {point})")

    problem = f"""\
;; {len(objectives)} objectives, {waypoints} waypoints, seed {seed}
(define (problem rovers-{len(objectives)}-{seed})
  (:domain rovers)
  (:objects
    rover1 - rover
    {' '.join(points)} - waypoint
    {' '.join(objectives)} - objective)
  (:init
    {chr(10).join('    ' + f for f in sorted(set(init))).strip()})
  (:goal (and
    {chr(10).join(f'    (reported {o})' for o in objectives).strip()})))
"""
    return ROVERS_DOMAIN, problem


# --------------------------------------------------------------------------
# numeric transport
# --------------------------------------------------------------------------
NUMERIC_DOMAIN = """\
;; Transport with fuel -- exercises numeric fluents.
(define (domain numeric-transport)
  (:requirements :strips :typing :numeric-fluents)
  (:types truck location package - object)
  (:predicates
    (at ?t - truck ?l - location)
    (road ?a ?b - location)
    (carrying ?p - package ?t - truck)
    (package-at ?p - package ?l - location))
  (:functions
    (fuel ?t - truck)
    (distance ?a ?b - location))

  (:action drive
    :parameters (?t - truck ?from ?to - location)
    :precondition (and (at ?t ?from) (road ?from ?to)
                       (>= (fuel ?t) (distance ?from ?to)))
    :effect (and (not (at ?t ?from)) (at ?t ?to)
                 (decrease (fuel ?t) (distance ?from ?to))))

  (:action refuel
    :parameters (?t - truck)
    :precondition (< (fuel ?t) 40)
    :effect (assign (fuel ?t) 60))

  (:action load
    :parameters (?p - package ?t - truck ?l - location)
    :precondition (and (at ?t ?l) (package-at ?p ?l))
    :effect (and (not (package-at ?p ?l)) (carrying ?p ?t)))

  (:action unload
    :parameters (?p - package ?t - truck ?l - location)
    :precondition (and (at ?t ?l) (carrying ?p ?t))
    :effect (and (not (carrying ?p ?t)) (package-at ?p ?l))))
"""


def generate_numeric_transport(size: int = 2, seed: int = 0, locations: int = 4):
    """``size`` packages on a fuel-limited road network."""
    rng = random.Random(seed)
    locations = max(2, locations)
    places = _objects("loc", locations)
    packages = _objects("pkg", max(1, size))

    init = ["(at truck1 loc1)", "(= (fuel truck1) 50)"]
    for a, b in zip(places, places[1:]):
        distance = rng.choice([10, 15, 20])
        init.append(f"(road {a} {b})")
        init.append(f"(road {b} {a})")
        init.append(f"(= (distance {a} {b}) {distance})")
        init.append(f"(= (distance {b} {a}) {distance})")

    goals = []
    for package in packages:
        init.append(f"(package-at {package} {places[0]})")
        goals.append(f"(package-at {package} {places[-1]})")

    problem = f"""\
;; {len(packages)} packages, {locations} locations, seed {seed}
(define (problem numeric-transport-{len(packages)}-{seed})
  (:domain numeric-transport)
  (:objects
    truck1 - truck
    {' '.join(places)} - location
    {' '.join(packages)} - package)
  (:init
    {chr(10).join('    ' + f for f in init).strip()})
  (:goal (and
    {chr(10).join('    ' + g for g in goals).strip()})))
"""
    return NUMERIC_DOMAIN, problem


# --------------------------------------------------------------------------
# temporal workshop
# --------------------------------------------------------------------------
TEMPORAL_DOMAIN = """\
;; Workshop -- exercises durative actions (sequential compilation).
(define (domain workshop)
  (:requirements :strips :typing :durative-actions)
  (:types part - object)
  (:predicates
    (cut ?p - part)
    (drilled ?p - part)
    (painted ?p - part)
    (finished ?p - part))

  (:durative-action cut
    :parameters (?p - part)
    :duration (= ?duration 2)
    :condition (and (at start (not (cut ?p))))
    :effect (and (at end (cut ?p))))

  (:durative-action drill
    :parameters (?p - part)
    :duration (= ?duration 3)
    :condition (and (over all (cut ?p)))
    :effect (and (at end (drilled ?p))))

  (:durative-action paint
    :parameters (?p - part)
    :duration (= ?duration 5)
    :condition (and (over all (drilled ?p)))
    :effect (and (at end (painted ?p))))

  (:durative-action inspect
    :parameters (?p - part)
    :duration (= ?duration 1)
    :condition (and (over all (painted ?p)))
    :effect (and (at end (finished ?p)))))
"""


def generate_temporal_workshop(size: int = 2, seed: int = 0):
    """``size`` parts through a cut/drill/paint/inspect pipeline, with durations."""
    parts = _objects("part", max(1, size))
    problem = f"""\
;; {len(parts)} parts, seed {seed}
(define (problem workshop-{len(parts)}-{seed})
  (:domain workshop)
  (:objects {' '.join(parts)} - part)
  (:init )
  (:goal (and
    {chr(10).join(f'    (finished {p})' for p in parts).strip()})))
"""
    return TEMPORAL_DOMAIN, problem


# --------------------------------------------------------------------------
# random STRIPS
# --------------------------------------------------------------------------
def generate_random_strips(
    size: int = 8,
    seed: int = 0,
    actions: int = 10,
    goal_size: int = 3,
):
    """A random STRIPS instance built backwards from a guaranteed solution.

    Purely random operators almost always give an unsolvable problem, which
    makes for a useless benchmark. Instead this plants a random *chain*: each
    step in the chain has an action that turns the previous state into the next,
    so a plan of known length exists. The remaining actions are noise the
    planner has to search past.
    """
    rng = random.Random(seed)
    size = max(4, size)
    facts = [f"p{i + 1}" for i in range(size)]
    chain_length = max(2, min(actions // 2, size))

    init_facts = set(rng.sample(facts, max(1, size // 3)))
    state = set(init_facts)
    operators = []

    # --- the planted solution ---------------------------------------------
    for step in range(chain_length):
        candidates = [f for f in facts if f not in state]
        if not candidates:
            break
        added = rng.choice(candidates)
        precondition = sorted(rng.sample(sorted(state), min(2, len(state))))
        deleted = []
        if len(state) > 1 and rng.random() < 0.4:
            deleted = [
                (
                    rng.choice([f for f in sorted(state) if f not in precondition])
                    if len(state) > len(precondition)
                    else None
                )
            ]
            deleted = [d for d in deleted if d]
        operators.append((f"solve{step + 1}", precondition, [added], deleted))
        state.add(added)
        state.difference_update(deleted)

    goal_facts = sorted(rng.sample(sorted(state), min(goal_size, len(state))))

    # --- distractors -------------------------------------------------------
    for index in range(max(0, actions - len(operators))):
        precondition = sorted(rng.sample(facts, rng.randint(1, 2)))
        added = sorted(rng.sample(facts, rng.randint(1, 2)))
        deleted = [f for f in rng.sample(facts, 1) if f not in added]
        operators.append((f"noise{index + 1}", precondition, added, deleted))

    def action_text(name, pre, add, delete):
        conditions = " ".join(f"({p})" for p in pre) or ""
        effects = " ".join(f"({a})" for a in add)
        effects += " " + " ".join(f"(not ({d}))" for d in delete)
        return (
            f"  (:action {name}\n"
            f"    :precondition (and {conditions})\n"
            f"    :effect (and {effects.strip()}))"
        )

    domain = "\n".join(
        [
            ";; Random STRIPS -- generated by jupyddl.generator",
            f"(define (domain random-strips-{size}-{seed})",
            "  (:requirements :strips)",
            "  (:predicates " + " ".join(f"({f})" for f in facts) + ")",
            "",
            "\n\n".join(action_text(*op) for op in operators),
            ")",
        ]
    )
    problem = f"""\
;; {size} facts, {len(operators)} actions, seed {seed}
(define (problem random-strips-{size}-{seed})
  (:domain random-strips-{size}-{seed})
  (:init {' '.join(f'({f})' for f in sorted(init_facts))})
  (:goal (and {' '.join(f'({f})' for f in goal_facts)})))
"""
    return domain, problem


# --------------------------------------------------------------------------
# registry
# --------------------------------------------------------------------------
GENERATORS = {
    "blocksworld": generate_blocksworld,
    "gripper": generate_gripper,
    "logistics": generate_logistics,
    "rovers": generate_rovers,
    "numeric-transport": generate_numeric_transport,
    "workshop": generate_temporal_workshop,
    "random-strips": generate_random_strips,
}

# What each generator is meant to stress, for the CLI and the playground.
GENERATOR_NOTES = {
    "blocksworld": "Classic block stacking. Deep plans, heavy plateaus.",
    "gripper": "Balls between two rooms. High branching factor.",
    "logistics": "Trucks and a plane with action costs.",
    "rovers": "ADL: disjunctive and existential preconditions.",
    "numeric-transport": "Numeric fluents: fuel consumption and refuelling.",
    "workshop": "Durative actions; plans report a makespan.",
    "random-strips": "Random operators around a planted solution chain.",
}


def generate(kind: str, size: int = 4, seed: int = 0, **kwargs):
    """Generate ``(domain_text, problem_text)`` for a named generator."""
    try:
        factory = GENERATORS[kind]
    except KeyError:
        raise ValueError(
            f"Unknown generator '{kind}'. Available: {sorted(GENERATORS)}"
        ) from None
    return factory(size=size, seed=seed, **kwargs)


def describe_generators() -> list:
    """Serialisable metadata for the CLI and the web workbench."""
    return [
        {"name": name, "summary": GENERATOR_NOTES.get(name, "")}
        for name in sorted(GENERATORS)
    ]


def write_instance(
    kind: str,
    folder: str,
    size: int = 4,
    seed: int = 0,
    name: Optional[str] = None,
    **kwargs,
) -> str:
    """Generate an instance and write ``<folder>/<name>/{domain,problem}.pddl``."""
    import os

    domain, problem = generate(kind, size=size, seed=seed, **kwargs)
    target = os.path.join(folder, name or f"{kind}-{size:02d}-{seed}")
    os.makedirs(target, exist_ok=True)
    with open(os.path.join(target, "domain.pddl"), "w", encoding="utf-8") as handle:
        handle.write(domain)
    with open(os.path.join(target, "problem.pddl"), "w", encoding="utf-8") as handle:
        handle.write(problem)
    return target
